version: "3.8"

services:
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: domus
      MYSQL_USER: springboot
      MYSQL_PASSWORD: domus_20
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
      
  rest-api:
    image: registry.gitlab.com/tqs-domus/rest-api
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/domus?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: springboot
      SPRING_DATASOURCE_PASSWORD: domus_20
    networks:
      - all

volumes:
  db-data:

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
