version: "3.8"

services:
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: domus
      MYSQL_USER: springboot
      MYSQL_PASSWORD: domus_20
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
      
  rest-api:
    image: registry.gitlab.com/tqs-domus/rest-api
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/domus?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: springboot
      SPRING_DATASOURCE_PASSWORD: domus_20
  
  web-app:
    image: registry.gitlab.com/tqs-domus/web-application
    ports:
      - "3000:3000"
    depends_on:
      - rest-api

volumes:
  db-data:
